feat: docker setup
krispy-clean/hackathon pull request #7
Opened 2024-07-01 13:14 UTC by cedricgautier

## Done
- Setup is added database, database admin portal

2024-07-01 13:32 UTC, BarnabePILLIAUDIN requested changes
?

2024-07-01 13:32 UTC, BarnabePILLIAUDIN commented on Makefile
> +	@cd back && bunx prettier . -c && bunx eslint .
Please use the ci check script for front. You may need to create it for back.

2024-07-01 13:32 UTC, BarnabePILLIAUDIN commented on Makefile
> +	@cd front && bunx prettier . -w
Please use the npm script

2024-07-01 13:32 UTC, BarnabePILLIAUDIN commented on docker-compose-dev.yml
> +    volumes:
Would it be more simple to share the whole folder ?

2024-07-01 13:32 UTC, BarnabePILLIAUDIN commented on docker-compose-dev.yml
What is the difference between Mongo and Mongo express ?

2024-07-01 13:38 UTC, cedricgautier commented on docker-compose-dev.yml
Mongo is the database and Mongo Express is the Admin Panel

2024-07-01 13:38 UTC, BarnabePILLIAUDIN commented on Makefile
> +	@cd back && bunx prettier . -c && bunx eslint .
> Please use the ci check script for front. You may need to create it for back.

```suggestion
	@cd back && bun run format-check && bun run lint
```

2024-07-01 13:39 UTC, cedricgautier commented on docker-compose-dev.yml
> +    volumes:
But that would mean to share everything that might not be necessary

2024-07-01 13:39 UTC, BarnabePILLIAUDIN commented on Makefile
> +	@cd front && bunx prettier . -w
> Please use the npm script

```suggestion
	@cd front && bun run format-fix
```

2024-07-01 14:27 UTC, Gougoh submitted a review, later dismissed

2024-07-01 14:29 UTC, BarnabePILLIAUDIN commented on docker-compose-dev.yml
> +    volumes:
Yes but it it can prevent bugs like we had on airneis if we use a new file that is not shared.

2024-07-01 14:31 UTC, BarnabePILLIAUDIN commented on docker-compose-dev.yml
Would it be more secure to use table plus / compas

2024-07-01 14:38 UTC, cedricgautier commented on docker-compose-dev.yml
You can use whatever you want, but we'll take into account what mongo provides too

2024-07-01 14:39 UTC, cedricgautier commented on docker-compose-dev.yml
It's not going to be more secure as it's dev env

2024-07-02 07:34 UTC, Gougoh submitted a review, later dismissed

2024-07-02 13:06 UTC, BarnabePILLIAUDIN approved these changes
LGTM

2024-07-02 15:58 UTC, merged